import 'package:flutter/material.dart';

// Cung cấp ngữ cảnh ngôn ngữ cho toàn ứng dụng
class LanguageProvider extends InheritedWidget {
  final Locale currentLocale;
  final String currentLanguageCode;
  final Function(String) changeLanguage;
  final String Function(String) getLanguageName;
  final String Function(String) translate;
  
  const LanguageProvider({
    super.key,
    required this.currentLocale,
    required this.currentLanguageCode,
    required this.changeLanguage,
    required this.getLanguageName,
    required this.translate,
    required super.child,
  });
  
  // Truy cập tiện lợi tới LanguageProvider trong cây widget
  static LanguageProvider? of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<LanguageProvider>();
  }
  
  @override
  // Khi mã ngôn ngữ thay đổi thì các widget con cần rebuild
  bool updateShouldNotify(LanguageProvider oldWidget) {
    return currentLanguageCode != oldWidget.currentLanguageCode;
  }
}

// Quản lý trạng thái ngôn ngữ và bảng dịch đơn giản
class LanguageManager {
  static Locale _currentLocale = const Locale('en', 'US');
  static VoidCallback? _onLanguageChanged;
  
  static Locale get currentLocale => _currentLocale;
  
  static String get currentLanguageCode => _currentLocale.languageCode;
  
  static void setOnLanguageChanged(VoidCallback callback) {
    _onLanguageChanged = callback;
  }
  
  // Đổi ngôn ngữ theo mã (vi, en, es, fr)
  static void changeLanguage(String languageCode) {
    switch (languageCode) {
      case 'vi':
        _currentLocale = const Locale('vi', 'VN');
        break;
      case 'es':
        _currentLocale = const Locale('es', 'ES');
        break;
      case 'fr':
        _currentLocale = const Locale('fr', 'FR');
        break;
      default:
        _currentLocale = const Locale('en', 'US');
    }
    // Gọi callback để rebuild ứng dụng
    _onLanguageChanged?.call();
  }
  
  // Trả về tên hiển thị của ngôn ngữ
  static String getLanguageName(String languageCode) {
    switch (languageCode) {
      case 'en':
        return 'English';
      case 'vi':
        return 'Tiếng Việt';
      case 'es':
        return 'Español';
      case 'fr':
        return 'Français';
      default:
        return 'English';
    }
  }
  
  // Hàm dịch khoá chuỗi dựa vào ngôn ngữ hiện tại
  static String translate(String key) {
    switch (_currentLocale.languageCode) {
      case 'vi':
        return _vietnameseTranslations[key] ?? key;
      case 'es':
        return _spanishTranslations[key] ?? key;
      case 'fr':
        return _frenchTranslations[key] ?? key;
      default:
        return _englishTranslations[key] ?? key;
    }
  }
  
  // Bảng dịch tiếng Anh
  static const Map<String, String> _englishTranslations = {
    'app_title': 'StoryVerse - Your Reading Adventure',
    'home': 'Home',
    'explore': 'Explore',
    'book_list': 'Book List',
    'profile': 'Profile',
    'welcome_back': 'Welcome back,',
    'guest_user': 'Guest User',
    'guest_account': 'Guest Account',
    'book_enthusiast': 'Book Enthusiast',
    'reading_statistics': 'Reading Statistics',
    'books_read': 'Books Read',
    'pages_read': 'Pages Read',
    'reading_streak': 'Reading Streak',
    'hours_read': 'Hours Read',
    'avg_rating': 'Avg Rating',
    'genres': 'Genres',
    'achievements': 'Achievements',
    'reading_goals': 'Reading Goals',
    'books_this_year': 'Books this year',
    'pages_this_month': 'Pages this month',
    'days': 'days',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'manage_notifications': 'Manage your notification preferences',
    'dark_mode': 'Dark Mode',
    'switch_dark_theme': 'Switch to dark theme',
    'language': 'Language',
    'select_language': 'Select Language',
    'font_size': 'Font Size',
    'reading_reminders': 'Reading Reminders',
    'about_storyverse': 'About StoryVerse',
    'version': 'Version',
    'help_support': 'Help & Support',
    'get_help': 'Get help and contact support',
    'privacy_policy': 'Privacy Policy',
    'read_privacy': 'Read our privacy policy',
    'log_in': 'Log In',
    'log_in_account': 'Log in to your account',
    'sign_out': 'Sign Out',
    'sign_out_account': 'Sign out of your account',
    'edit_profile': 'Edit Profile',
    'edit': 'Edit',
    'cancel': 'Cancel',
    'save': 'Save',
    'login_successful': 'Login successful!',
    'signout_successful': 'Signed out successfully!',
    'switch_dark_mode': 'Switched to Dark Mode!',
    'switch_light_mode': 'Switched to Light Mode!',
    'recommended_for_you': 'Recommended for you',
    'our_pick': 'Our Pick',
    'start_reading': 'Start Reading',
    'continue_reading': 'Continue Reading',
    'start_adventure': 'Start Your Adventure Through Stories',
    'discover_world': 'Discover a world of fantasy, action, and romance in hundreds of favorite novel and comic titles. One chapter can open up a whole new world!',
    'more_you_read': 'The more you read, the more you get!',
    'rewards_description': 'Every page you read can pave the way to exciting rewards. Keep reading, because every word you skip means something!',
    'find_story': 'Find a Story that Fits You',
    'story_description': 'From heartwarming romances to adrenaline-pumping adventures—explore a variety of genres and find the story you love the most!',
    'sign_in': 'Sign in',
    'enter_as_guest': 'Enter as guest',
    'create_account': 'Create Account',
    'already_have_account': 'Already have an account?',
    'sign_in_here': 'Sign in here',
    'email': 'Email',
    'password': 'Password',
    'email_or_username': 'Email or Username',
    'enter_email_or_username': 'Enter your email or username...',
    'email_or_username_required': 'Please enter your email or username.',
    'enter_password': 'Enter your password...',
    'password_required': 'Please enter your password.',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'continue_with_google': 'Continue with Google',
    'or_text': 'Or',
    'remember_me': 'Remember me',
    'sign_up': 'Sign Up',
    'dont_have_account': 'Don\'t have an account?',
    'sign_up_here': 'Sign up here',
    'small': 'Small',
    'medium': 'Medium',
    'large': 'Large',
    'extra_large': 'Extra Large',
    'my_library': 'My Library',
    'books': 'Books',
    'in_progress': 'In Progress',
    'completed': 'Completed',
    'last_read': 'Last read',
    'hours_ago': 'hours ago',
    'trending_now': 'Trending Now',
    'see_all': 'See all',
    'search_books': 'Search books, authors, genres...',
    'all': 'All',
    'fantasy': 'Fantasy',
    'sci_fi': 'Sci-Fi',
    'romance': 'Romance',
    'overview': 'Overview',
    'chapters': 'Chapters',
    'reviews': 'Reviews',
    'description': 'Description',
    'story_info': 'Story Info',
    'author': 'Author',
    'category': 'Category',
    'chapter_count': 'Chapter Count',
    'status': 'Status',
    'updating': 'Updating',
    'not_updated': 'Not updated',
    'no_description': 'No description available for this title.',
    'follow': 'Follow',
    'unfollow': 'Unfollow',
    'login_required_title': 'Login required',
    'login_required_message': 'Please log in to use this feature.',
    'decline': 'Decline',
    'pages': 'pages',
    'finished': 'Finished',
    'completed_status': 'Completed',
    'search_library': 'Search your library...',
    'sort_recent': 'Recent',
    'sort_title': 'Title',
    'sort_progress': 'Progress',
    'sort_rating': 'Rating',
    'error_prefix': 'Error:',
    'retry': 'Retry',
    'no_followed_title': 'No followed comics yet',
    'no_followed_subtitle': 'Follow a title to see it here.',
    'add_now': 'Add now',
    'no_completed_title': 'No completed titles yet',
    'no_completed_subtitle': 'Finish a title to see it here.',
    'read_now': 'Read now',
    'account_not_found': 'Account info not found',
    'comic_id_not_found': 'Comic ID not found',
    'generic_error': 'Something went wrong',
    'followed_success': 'Followed this comic',
    'unfollowed_success': 'Unfollowed this comic',
    'type': 'Type',
    'followed_status': 'Followed',
    'comic_not_found': 'Comic not found',
    'comic_not_found_long': 'This comic could not be found. It may have been removed or the slug is invalid.',
    'read_from_chapter': 'Read from chapter',
    'no_chapters': 'No chapters available',
    'mark_completed': 'Mark completed',
    'mark_incomplete': 'Mark in progress',
    'select_genre': 'Select genre',
    'clear_all': 'Clear all',
    'done': 'Done',
    'start_search_hint': 'Type a title or genre to start searching',
    'no_results': 'No results found',
    'try_other_genre_or_keyword': 'Try another genre or keyword',
    'try_other_keyword': 'Try another keyword',
    'explore_comic_world': 'Explore the world of comics',
    'featured_comics': 'Featured comics',
    'total_comics': 'Total comics',
    'comics_unit': 'Comics',
    'current_page': 'Current page',
    'pages_unit': 'Pages',
    'total_pages': 'Total pages',
    'recent_updates': 'Recent updates',
    'load_error': 'Load error',
    'new_comics_updated': 'New comics updated',
    'suggestion_prefix': 'Suggestion',
    'view': 'View',
  };
  
  // Bảng dịch tiếng Việt
  static const Map<String, String> _vietnameseTranslations = {
    'app_title': 'StoryVerse - Cuộc Phiêu Lưu Đọc Sách',
    'home': 'Trang Chủ',
    'explore': 'Khám Phá',
    'book_list': 'Danh Sách Sách',
    'profile': 'Hồ Sơ',
    'welcome_back': 'Chào mừng trở lại,',
    'guest_user': 'Người Dùng Khách',
    'guest_account': 'Tài Khoản Khách',
    'book_enthusiast': 'Người Yêu Sách',
    'reading_statistics': 'Thống Kê Đọc Sách',
    'books_read': 'Sách Đã Đọc',
    'pages_read': 'Trang Đã Đọc',
    'reading_streak': 'Chuỗi Đọc Sách',
    'hours_read': 'Giờ Đã Đọc',
    'avg_rating': 'Đánh Giá TB',
    'genres': 'Thể Loại',
    'achievements': 'Thành Tích',
    'reading_goals': 'Mục Tiêu Đọc Sách',
    'books_this_year': 'Sách năm nay',
    'pages_this_month': 'Trang tháng này',
    'days': 'ngày',
    'settings': 'Cài Đặt',
    'notifications': 'Thông Báo',
    'manage_notifications': 'Quản lý tùy chọn thông báo',
    'dark_mode': 'Chế Độ Tối',
    'switch_dark_theme': 'Chuyển sang chế độ tối',
    'language': 'Ngôn Ngữ',
    'select_language': 'Chọn Ngôn Ngữ',
    'font_size': 'Cỡ Chữ',
    'reading_reminders': 'Nhắc Nhở Đọc Sách',
    'about_storyverse': 'Về StoryVerse',
    'version': 'Phiên Bản',
    'help_support': 'Trợ Giúp & Hỗ Trợ',
    'get_help': 'Nhận trợ giúp và liên hệ hỗ trợ',
    'privacy_policy': 'Chính Sách Bảo Mật',
    'read_privacy': 'Đọc chính sách bảo mật của chúng tôi',
    'log_in': 'Đăng Nhập',
    'log_in_account': 'Đăng nhập vào tài khoản',
    'sign_out': 'Đăng Xuất',
    'sign_out_account': 'Đăng xuất khỏi tài khoản',
    'edit_profile': 'Chỉnh Sửa Hồ Sơ',
    'edit': 'Chỉnh Sửa',
    'cancel': 'Hủy',
    'save': 'Lưu',
    'login_successful': 'Đăng nhập thành công!',
    'signout_successful': 'Đăng xuất thành công!',
    'switch_dark_mode': 'Đã chuyển sang Chế Độ Tối!',
    'switch_light_mode': 'Đã chuyển sang Chế Độ Sáng!',
    'recommended_for_you': 'Được đề xuất cho bạn',
    'our_pick': 'Lựa chọn của chúng tôi',
    'start_reading': 'Bắt đầu đọc',
    'continue_reading': 'Tiếp tục đọc',
    'start_adventure': 'Bắt Đầu Cuộc Phiêu Lưu Qua Những Câu Chuyện',
    'discover_world': 'Khám phá thế giới của fantasy, hành động và lãng mạn trong hàng trăm tiêu đề tiểu thuyết và truyện tranh yêu thích. Một chương có thể mở ra cả một thế giới mới!',
    'more_you_read': 'Càng đọc nhiều, càng nhận được nhiều!',
    'rewards_description': 'Mỗi trang bạn đọc có thể mở đường cho những phần thưởng thú vị. Hãy tiếp tục đọc, vì mỗi từ bạn bỏ qua đều có ý nghĩa!',
    'find_story': 'Tìm Câu Chuyện Phù Hợp Với Bạn',
    'story_description': 'Từ những câu chuyện lãng mạn ấm áp đến những cuộc phiêu lưu đầy kịch tính—khám phá đa dạng thể loại và tìm câu chuyện bạn yêu thích nhất!',
    'sign_in': 'Đăng nhập',
    'enter_as_guest': 'Vào với tư cách khách',
    'create_account': 'Tạo tài khoản',
    'already_have_account': 'Đã có tài khoản?',
    'sign_in_here': 'Đăng nhập tại đây',
    'email': 'Email',
    'password': 'Mật khẩu',
    'email_or_username': 'Email hoặc Tên đăng nhập',
    'enter_email_or_username': 'Nhập email hoặc tên đăng nhập...',
    'email_or_username_required': 'Vui lòng nhập email hoặc tên đăng nhập.',
    'enter_password': 'Nhập mật khẩu của bạn...',
    'password_required': 'Vui lòng nhập mật khẩu của bạn.',
    'confirm_password': 'Xác nhận mật khẩu',
    'forgot_password': 'Quên mật khẩu?',
    'continue_with_google': 'Tiếp tục với Google',
    'or_text': 'Hoặc',
    'remember_me': 'Ghi nhớ tôi',
    'sign_up': 'Đăng ký',
    'dont_have_account': 'Chưa có tài khoản?',
    'sign_up_here': 'Đăng ký tại đây',
    'small': 'Nhỏ',
    'medium': 'Trung bình',
    'large': 'Lớn',
    'extra_large': 'Rất lớn',
    'my_library': 'Thư Viện Của Tôi',
    'books': 'Sách',
    'in_progress': 'Đang Đọc',
    'completed': 'Đã Hoàn Thành',
    'last_read': 'Lần đọc cuối',
    'hours_ago': 'giờ trước',
    'trending_now': 'Đang Thịnh Hành',
    'see_all': 'Xem tất cả',
    'search_books': 'Tìm kiếm sách, tác giả, thể loại...',
    'all': 'Tất cả',
    'fantasy': 'Fantasy',
    'sci_fi': 'Khoa học viễn tưởng',
    'romance': 'Lãng mạn',
    'overview': 'Tổng quan',
    'chapters': 'Chương',
    'reviews': 'Đánh giá',
    'description': 'Mô tả',
    'story_info': 'Thông tin truyện',
    'author': 'Tác giả',
    'category': 'Thể loại',
    'chapter_count': 'Số chương',
    'status': 'Trạng thái',
    'updating': 'Đang cập nhật',
    'not_updated': 'Chưa cập nhật',
    'no_description': 'Chưa có mô tả cho truyện này.',
    'follow': 'Yêu thích',
    'unfollow': 'Bỏ yêu thích',
    'login_required_title': 'Đăng nhập yêu cầu',
    'login_required_message': 'Bạn cần đăng nhập để sử dụng tính năng này.',
    'decline': 'Từ chối',
    'pages': 'trang',
    'finished': 'Hoàn thành',
    'completed_status': 'Hoàn thành',
    'search_library': 'Tìm kiếm trong thư viện...',
    'sort_recent': 'Gần đây',
    'sort_title': 'Tiêu đề',
    'sort_progress': 'Tiến độ',
    'sort_rating': 'Đánh giá',
    'error_prefix': 'Lỗi:',
    'retry': 'Thử lại',
    'no_followed_title': 'Chưa có truyện theo dõi',
    'no_followed_subtitle': 'Bấm thêm ngay để chọn truyện bạn muốn theo dõi.',
    'add_now': 'Thêm ngay',
    'no_completed_title': 'Chưa có truyện hoàn thành',
    'no_completed_subtitle': 'Hoàn thành truyện để xem chúng ở đây',
    'read_now': 'Đọc ngay',
    'account_not_found': 'Không tìm thấy thông tin tài khoản',
    'comic_id_not_found': 'Không tìm thấy ID truyện',
    'generic_error': 'Có lỗi xảy ra',
    'followed_success': 'Đã theo dõi truyện',
    'unfollowed_success': 'Đã bỏ theo dõi truyện',
    'type': 'Loại',
    'followed_status': 'Đã theo dõi',
    'comic_not_found': 'Không tìm thấy truyện',
    'comic_not_found_long': 'Không tìm thấy truyện này. Có thể đã bị xóa hoặc slug không đúng.',
    'read_from_chapter': 'Đọc từ chap',
    'no_chapters': 'Chưa có chương',
    'mark_completed': 'Đánh dấu hoàn thành',
    'mark_incomplete': 'Đánh dấu đang đọc',
    'select_genre': 'Chọn thể loại',
    'clear_all': 'Xóa tất cả',
    'done': 'Xong',
    'start_search_hint': 'Gõ tên truyện hoặc thể loại để bắt đầu tìm kiếm',
    'no_results': 'Không tìm thấy truyện nào',
    'try_other_genre_or_keyword': 'Thử chọn thể loại khác hoặc tìm kiếm với từ khóa khác',
    'try_other_keyword': 'Thử tìm kiếm với từ khóa khác',
    'explore_comic_world': 'Khám phá thế giới truyện tranh',
    'featured_comics': 'Truyện nổi bật',
    'total_comics': 'Tổng truyện',
    'comics_unit': 'Truyện',
    'current_page': 'Trang hiện tại',
    'pages_unit': 'Trang',
    'total_pages': 'Tổng trang',
    'recent_updates': 'Cập nhật gần đây',
    'load_error': 'Lỗi tải dữ liệu',
    'new_comics_updated': 'Có truyện mới cập nhật',
    'suggestion_prefix': 'Gợi ý',
    'view': 'Xem',
  };
  
  // Bảng dịch tiếng Tây Ban Nha
  static const Map<String, String> _spanishTranslations = {
    'app_title': 'StoryVerse - Tu Aventura de Lectura',
    'home': 'Inicio',
    'explore': 'Explorar',
    'book_list': 'Lista de Libros',
    'profile': 'Perfil',
    'welcome_back': 'Bienvenido de nuevo,',
    'guest_user': 'Usuario Invitado',
    'guest_account': 'Cuenta Invitada',
    'book_enthusiast': 'Entusiasta de Libros',
    'reading_statistics': 'Estadísticas de Lectura',
    'books_read': 'Libros Leídos',
    'pages_read': 'Páginas Leídas',
    'reading_streak': 'Racha de Lectura',
    'hours_read': 'Horas Leídas',
    'avg_rating': 'Calificación Promedio',
    'genres': 'Géneros',
    'achievements': 'Logros',
    'reading_goals': 'Objetivos de Lectura',
    'books_this_year': 'Libros este año',
    'pages_this_month': 'Páginas este mes',
    'days': 'días',
    'settings': 'Configuración',
    'notifications': 'Notificaciones',
    'manage_notifications': 'Gestiona tus preferencias de notificación',
    'dark_mode': 'Modo Oscuro',
    'switch_dark_theme': 'Cambiar a tema oscuro',
    'language': 'Idioma',
    'select_language': 'Seleccionar Idioma',
    'font_size': 'Tamaño de Fuente',
    'reading_reminders': 'Recordatorios de Lectura',
    'about_storyverse': 'Acerca de StoryVerse',
    'version': 'Versión',
    'help_support': 'Ayuda y Soporte',
    'get_help': 'Obtén ayuda y contacta soporte',
    'privacy_policy': 'Política de Privacidad',
    'read_privacy': 'Lee nuestra política de privacidad',
    'log_in': 'Iniciar Sesión',
    'log_in_account': 'Inicia sesión en tu cuenta',
    'sign_out': 'Cerrar Sesión',
    'sign_out_account': 'Cierra sesión de tu cuenta',
    'edit_profile': 'Editar Perfil',
    'edit': 'Editar',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'login_successful': '¡Inicio de sesión exitoso!',
    'signout_successful': '¡Sesión cerrada exitosamente!',
    'switch_dark_mode': '¡Cambiado a Modo Oscuro!',
    'switch_light_mode': '¡Cambiado a Modo Claro!',
    'recommended_for_you': 'Recomendado para ti',
    'our_pick': 'Nuestra elección',
    'start_reading': 'Comenzar a leer',
    'continue_reading': 'Continuar leyendo',
    'start_adventure': 'Comienza Tu Aventura a Través de Historias',
    'discover_world': 'Descubre un mundo de fantasía, acción y romance en cientos de títulos favoritos de novelas y cómics. ¡Un capítulo puede abrir todo un mundo nuevo!',
    'more_you_read': '¡Cuanto más leas, más obtienes!',
    'rewards_description': 'Cada página que leas puede allanar el camino hacia recompensas emocionantes. ¡Sigue leyendo, porque cada palabra que te saltes significa algo!',
    'find_story': 'Encuentra una Historia que Te Ajuste',
    'story_description': 'Desde romances conmovedores hasta aventuras llenas de adrenalina—¡explora una variedad de géneros y encuentra la historia que más amas!',
    'sign_in': 'Iniciar sesión',
    'enter_as_guest': 'Entrar como invitado',
    'create_account': 'Crear cuenta',
    'already_have_account': '¿Ya tienes una cuenta?',
    'sign_in_here': 'Inicia sesión aquí',
    'email': 'Correo electrónico',
    'password': 'Contraseña',
    'email_or_username': 'Correo o usuario',
    'enter_email_or_username': 'Ingresa tu correo o usuario...',
    'email_or_username_required': 'Por favor ingresa tu correo o usuario.',
    'enter_password': 'Ingresa tu contraseña...',
    'password_required': 'Por favor ingresa tu contraseña.',
    'confirm_password': 'Confirmar contraseña',
    'forgot_password': '¿Olvidaste tu contraseña?',
    'continue_with_google': 'Continuar con Google',
    'or_text': 'O',
    'remember_me': 'Recordarme',
    'sign_up': 'Registrarse',
    'dont_have_account': '¿No tienes una cuenta?',
    'sign_up_here': 'Regístrate aquí',
    'small': 'Pequeño',
    'medium': 'Mediano',
    'large': 'Grande',
    'extra_large': 'Extra Grande',
    'my_library': 'Mi Biblioteca',
    'books': 'Libros',
    'in_progress': 'En Progreso',
    'completed': 'Completado',
    'last_read': 'Última lectura',
    'hours_ago': 'hace horas',
    'trending_now': 'Tendencia Ahora',
    'see_all': 'Ver todo',
    'search_books': 'Buscar libros, autores, géneros...',
    'all': 'Todos',
    'fantasy': 'Fantasía',
    'sci_fi': 'Ciencia Ficción',
    'romance': 'Romance',
    'overview': 'Overview',
    'chapters': 'Chapters',
    'reviews': 'Reviews',
    'description': 'Description',
    'story_info': 'Story Info',
    'author': 'Author',
    'category': 'Category',
    'chapter_count': 'Chapter Count',
    'status': 'Status',
    'updating': 'Updating',
    'not_updated': 'Not updated',
    'no_description': 'No description available for this title.',
    'follow': 'Follow',
    'unfollow': 'Unfollow',
    'login_required_title': 'Login required',
    'login_required_message': 'Please log in to use this feature.',
    'decline': 'Decline',
    'pages': 'pages',
    'finished': 'Finished',
    'completed_status': 'Completed',
    'search_library': 'Search your library...',
    'sort_recent': 'Recent',
    'sort_title': 'Title',
    'sort_progress': 'Progress',
    'sort_rating': 'Rating',
    'error_prefix': 'Error:',
    'retry': 'Retry',
    'no_followed_title': 'No followed comics yet',
    'no_followed_subtitle': 'Follow a title to see it here.',
    'add_now': 'Add now',
    'no_completed_title': 'No completed titles yet',
    'no_completed_subtitle': 'Finish a title to see it here.',
    'read_now': 'Read now',
    'account_not_found': 'Account info not found',
    'comic_id_not_found': 'Comic ID not found',
    'generic_error': 'Something went wrong',
    'followed_success': 'Followed this comic',
    'unfollowed_success': 'Unfollowed this comic',
    'type': 'Type',
    'followed_status': 'Followed',
    'comic_not_found': 'Comic not found',
    'comic_not_found_long': 'This comic could not be found. It may have been removed or the slug is invalid.',
    'read_from_chapter': 'Read from chapter',
    'no_chapters': 'No chapters available',
    'mark_completed': 'Mark completed',
    'mark_incomplete': 'Mark in progress',
    'select_genre': 'Select genre',
    'clear_all': 'Clear all',
    'done': 'Done',
    'start_search_hint': 'Type a title or genre to start searching',
    'no_results': 'No results found',
    'try_other_genre_or_keyword': 'Try another genre or keyword',
    'try_other_keyword': 'Try another keyword',
    'explore_comic_world': 'Explore the world of comics',
    'featured_comics': 'Featured comics',
    'total_comics': 'Total comics',
    'comics_unit': 'Comics',
    'current_page': 'Current page',
    'pages_unit': 'Pages',
    'total_pages': 'Total pages',
    'recent_updates': 'Recent updates',
    'load_error': 'Load error',
    'new_comics_updated': 'New comics updated',
    'suggestion_prefix': 'Suggestion',
    'view': 'View',
  };
  
  // Bảng dịch tiếng Pháp
  static const Map<String, String> _frenchTranslations = {
    'app_title': 'StoryVerse - Votre Aventura de Lecture',
    'home': 'Accueil',
    'explore': 'Explorer',
    'book_list': 'Liste des Livres',
    'profile': 'Profil',
    'welcome_back': 'Bon retour,',
    'guest_user': 'Utilisateur Invité',
    'guest_account': 'Compte Invité',
    'book_enthusiast': 'Passionné de Livres',
    'reading_statistics': 'Statistiques de Lecture',
    'books_read': 'Livres Lus',
    'pages_read': 'Pages Lues',
    'reading_streak': 'Série de Lecture',
    'hours_read': 'Heures Lues',
    'avg_rating': 'Note Moyenne',
    'genres': 'Genres',
    'achievements': 'Réalisations',
    'reading_goals': 'Objectifs de Lecture',
    'books_this_year': 'Livres cette année',
    'pages_this_month': 'Pages ce mois',
    'days': 'jours',
    'settings': 'Paramètres',
    'notifications': 'Notifications',
    'manage_notifications': 'Gérez vos préférences de notification',
    'dark_mode': 'Mode Sombre',
    'switch_dark_theme': 'Passer au thème sombre',
    'language': 'Langue',
    'select_language': 'Sélectionner la Langue',
    'font_size': 'Taille de Police',
    'reading_reminders': 'Rappels de Lecture',
    'about_storyverse': 'À Propos de StoryVerse',
    'version': 'Version',
    'help_support': 'Aide et Support',
    'get_help': 'Obtenez de l\'aide et contactez le support',
    'privacy_policy': 'Politique de Confidentialité',
    'read_privacy': 'Lisez notre politique de confidentialité',
    'log_in': 'Se Connecter',
    'log_in_account': 'Connectez-vous à votre compte',
    'sign_out': 'Se Déconnecter',
    'sign_out_account': 'Déconnectez-vous de votre compte',
    'edit_profile': 'Modifier le Profil',
    'edit': 'Modifier',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'login_successful': 'Connexion réussie !',
    'signout_successful': 'Déconnexion réussie !',
    'switch_dark_mode': 'Passé en Mode Sombre !',
    'switch_light_mode': 'Passé en Mode Clair !',
    'recommended_for_you': 'Recommandé pour vous',
    'our_pick': 'Notre choix',
    'start_reading': 'Commencer à lire',
    'continue_reading': 'Continuer à lire',
    'start_adventure': 'Commencez Votre Aventure à Travers les Histoires',
    'discover_world': 'Découvrez un monde de fantasy, d\'action et de romance dans des centaines de titres de romans et de bandes dessinées préférés. Un chapitre peut ouvrir tout un nouveau monde !',
    'more_you_read': 'Plus vous lisez, plus vous obtenez !',
    'rewards_description': 'Chaque page que vous lisez peut ouvrir la voie à des récompenses passionnantes. Continuez à lire, car chaque mot que vous sautez signifie quelque chose !',
    'find_story': 'Trouvez une Histoire qui Vous Convient',
    'story_description': 'Des romances réconfortantes aux aventures pleines d\'adrénaline—explorez une variété de genres et trouvez l\'histoire que vous aimez le plus !',
    'sign_in': 'Se connecter',
    'enter_as_guest': 'Entrer en tant qu\'invité',
    'create_account': 'Créer un compte',
    'already_have_account': 'Vous avez déjà un compte ?',
    'sign_in_here': 'Connectez-vous ici',
    'email': 'E-mail',
    'password': 'Mot de passe',
    'email_or_username': 'Email ou Nom d\'utilisateur',
    'enter_email_or_username': 'Entrez votre email ou nom d\'utilisateur...',
    'email_or_username_required': 'Veuillez entrer votre email ou nom d\'utilisateur.',
    'enter_password': 'Entrez votre mot de passe...',
    'password_required': 'Veuillez entrer votre mot de passe.',
    'confirm_password': 'Confirmer le mot de passe',
    'forgot_password': 'Mot de passe oublié ?',
    'continue_with_google': 'Continuer avec Google',
    'or_text': 'Ou',
    'remember_me': 'Se souvenir de moi',
    'sign_up': 'S\'inscrire',
    'dont_have_account': 'Vous n\'avez pas de compte ?',
    'sign_up_here': 'Inscrivez-vous ici',
    'small': 'Petit',
    'medium': 'Moyen',
    'large': 'Grand',
    'extra_large': 'Très Grand',
    'my_library': 'Ma Bibliothèque',
    'books': 'Livres',
    'in_progress': 'En Cours',
    'completed': 'Terminé',
    'last_read': 'Dernière lecture',
    'hours_ago': 'il y a heures',
    'trending_now': 'Tendance Maintenant',
    'see_all': 'Voir tout',
    'search_books': 'Rechercher des livres, auteurs, genres...',
    'all': 'Tous',
    'fantasy': 'Fantaisie',
    'sci_fi': 'Science-Fiction',
    'romance': 'Romance',
    'overview': 'Overview',
    'chapters': 'Chapters',
    'reviews': 'Reviews',
    'description': 'Description',
    'story_info': 'Story Info',
    'author': 'Author',
    'category': 'Category',
    'chapter_count': 'Chapter Count',
    'status': 'Status',
    'updating': 'Updating',
    'not_updated': 'Not updated',
    'no_description': 'No description available for this title.',
    'follow': 'Follow',
    'unfollow': 'Unfollow',
    'login_required_title': 'Login required',
    'login_required_message': 'Please log in to use this feature.',
    'decline': 'Decline',
    'pages': 'pages',
    'finished': 'Finished',
    'completed_status': 'Completed',
    'search_library': 'Search your library...',
    'sort_recent': 'Recent',
    'sort_title': 'Title',
    'sort_progress': 'Progress',
    'sort_rating': 'Rating',
    'error_prefix': 'Error:',
    'retry': 'Retry',
    'no_followed_title': 'No followed comics yet',
    'no_followed_subtitle': 'Follow a title to see it here.',
    'add_now': 'Add now',
    'no_completed_title': 'No completed titles yet',
    'no_completed_subtitle': 'Finish a title to see it here.',
    'read_now': 'Read now',
    'account_not_found': 'Account info not found',
    'comic_id_not_found': 'Comic ID not found',
    'generic_error': 'Something went wrong',
    'followed_success': 'Followed this comic',
    'unfollowed_success': 'Unfollowed this comic',
    'type': 'Type',
    'followed_status': 'Followed',
    'comic_not_found': 'Comic not found',
    'comic_not_found_long': 'This comic could not be found. It may have been removed or the slug is invalid.',
    'read_from_chapter': 'Read from chapter',
    'no_chapters': 'No chapters available',
    'mark_completed': 'Mark completed',
    'mark_incomplete': 'Mark in progress',
    'select_genre': 'Select genre',
    'clear_all': 'Clear all',
    'done': 'Done',
    'start_search_hint': 'Type a title or genre to start searching',
    'no_results': 'No results found',
    'try_other_genre_or_keyword': 'Try another genre or keyword',
    'try_other_keyword': 'Try another keyword',
    'explore_comic_world': 'Explore the world of comics',
    'featured_comics': 'Featured comics',
    'total_comics': 'Total comics',
    'comics_unit': 'Comics',
    'current_page': 'Current page',
    'pages_unit': 'Pages',
    'total_pages': 'Total pages',
    'recent_updates': 'Recent updates',
    'load_error': 'Load error',
    'new_comics_updated': 'New comics updated',
    'suggestion_prefix': 'Suggestion',
    'view': 'View',
  };
}
